<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dev.reuise</groupId>
  <artifactId>reuise-web-core</artifactId>
  <version>0.7.4-beta</version>
  <name>Reuise for Java (Web)</name>
  <distributionManagement>
    <repository>
      <id>github-reuise-web-core</id>
      <name>GitHub Packages</name>
      <url>https://maven.pkg.github.com/reuise/reuise-java-web-core</url>
    </repository>
  </distributionManagement>
  <properties>
    <maven.compiler.target>17</maven.compiler.target>
    <java.version>17</java.version>
    <maven.compiler.source>17</maven.compiler.source>
  </properties>
  <dependencies>
    <dependency>
      <groupId>dev.reuise</groupId>
      <artifactId>reuise-core</artifactId>
      <version>0.7.4-beta</version>
    </dependency>
    <dependency>
      <groupId>dev.reuise</groupId>
      <artifactId>reuise-webstyles</artifactId>
      <version>0.7.4-beta</version>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <id>local-mirror</id>
      <url>file://${user.home}/.m2/repository</url>
    </repository>
    <repository>
      <id>github-reuise-core</id>
      <url>https://maven.pkg.github.com/reuise/reuise-java-core</url>
    </repository>
    <repository>
      <id>github-reuise-webstyles</id>
      <url>https://maven.pkg.github.com/reuise/reuise-java-webstyles</url>
    </repository>
  </repositories>
  <build>
    <sourceDirectory>${basedir}/src/main/java</sourceDirectory>
    <outputDirectory>${basedir}/target/classes</outputDirectory>
    <resources>
      <resource>
        <directory>src/main/java</directory>
        <includes>
          <include>**/*.java</include>
          <include>**/*.gwt.xml</include>
        </includes>
      </resource>
      <resource>
        <directory>src/main/super</directory>
        <includes>
          <include>**/*.java</include>
          <include>**/*.gwt.xml</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.3.0</version>
      </plugin>
    </plugins>
  </build>
</project>
