package dev.reuise.web.core.scrollablecontainer;
import dev.reuise.core.scrollablecontainer.CoreScrollableContainerScrollAreaFeatures;
public interface WebScrollableContainerScrollAreaFeatures extends CoreScrollableContainerScrollAreaFeatures {}